function generateKUKALinearSRC(filename, positions, velocities)
    % positions is an Nx3 matrix with columns X, Y, Z
    % velocities is an Nx1 vector with velocities
    
    % Format the file name without the extension
    [~, base_name, ~] = fileparts(filename);

    % Open the file for writing
    filename_full = strcat(base_name, '.src');

    % Open file for writing
    fid = fopen(filename_full, 'w');
    disp(base_name)

    positions = positions(2:end,:);

        if size(velocities, 1) == 1 && size(velocities, 2) > 1  % Check if x is a row vector (1, n)
          velocities = velocities';  % Transpose and store back in data_sets
        end

    % % Extract the base file name without the extension
    % % [~, base_name, ~] = fileparts(filename);
    % base_name= string(filename);
  
    % File Header
    fprintf(fid, '&ACCESS RVP\n');
    fprintf(fid, '&REL 1\n');
    fprintf(fid, '&COMMENT Generated by RoboDK\n');
    fprintf(fid, '&PARAM TEMPLATE = generateKUKALinearSRC.m\n');
    fprintf(fid, '&PARAM EDITMASK = *\n');
    
    % Define Program Header
    fprintf(fid, 'DEF %s ( )\n', base_name);
    fprintf(fid, ';FOLD INI\n');
    fprintf(fid, 'BAS (#INITMOV,0 )\n');
    fprintf(fid, ';ENDFOLD (INI)\n\n');
    % fprintf(fid, '$OUT[1] = FALSE\n');
    fprintf(fid, "OUT 1 '' STATE=FALSE\n");
    
    % Start Position and Setup
    fprintf(fid, ';FOLD STARTPOS\n');
    fprintf(fid, '$BWDSTART = FALSE\n');
    fprintf(fid, 'PDAT_ACT = {VEL 50,ACC 100,APO_DIST 10}\n');
    fprintf(fid, 'BAS(#PTP_DAT)\n');
    fprintf(fid, 'FDAT_ACT = {TOOL_NO 4,BASE_NO 0,IPO_FRAME #BASE}\n');
    fprintf(fid, 'BAS (#FRAMES)\n');
    fprintf(fid, 'BAS (#VEL_PTP,50)\n');
    fprintf(fid, ';ENDFOLD\n\n\n');
    
    % Default speed
    fprintf(fid, ';FOLD SET DEFAULT SPEED\n');
    fprintf(fid, '$VEL.CP=0.2\n');
    fprintf(fid, 'BAS(#VEL_PTP,50)\n');
    fprintf(fid, 'BAS(#TOOL,0)\n');
    fprintf(fid, 'BAS(#BASE,0)\n');
    fprintf(fid, ';ENDFOLD\n\n');

    % Start Position move
    fprintf(fid, ';FOLD PTP FIRST POSITION\n');
    fprintf(fid, '$BWDSTART = FALSE\n');
    fprintf(fid, 'PDAT_ACT = {VEL 50,ACC 100,APO_DIST 10}\n');
    fprintf(fid, 'FDAT_ACT = {TOOL_NO 4,BASE_NO 0,IPO_FRAME #BASE}\n');
    fprintf(fid, 'BAS(#FRAMES)\n');
    fprintf(fid, '$ADVANCE = 5\n');
    fprintf(fid, ';ENDFOLD\n\n');
    
    fprintf(fid, 'PTP $AXIS_ACT ; skip BCO quickly\n\n');

    fprintf(fid, 'TOOL_DATA[4] = {FRAME: X 800.000,Y 0.000,Z 90.000,A 180.000,B -90.000,C 0.000}\n');

    fprintf(fid, '; --------------------------\n');
    fprintf(fid, '$VEL.ORI1 = 10.00000\n');
    fprintf(fid, '$VEL.ORI2 = 10.00000\n');
    fprintf(fid, '$VEL.CP = 0.02000\n');

% ----------------------------------------- EDITS-------------------%
% first move
        fprintf(fid, ';FOLD LIN P%d CONT Vel=%.5f m/s CPDAT%d Tool[4] Base[1];%%{PE}%%R 8.3.42,%%MKUKATPBASIS,%%CMOVE,%%VLIN,%%P 1:LIN, 2:P%d, 3:, 5:%.5f, 7:CPDAT%d\n', 2, 0.0500, 2, 2, 0.0500, 2);
        fprintf(fid, '$BWDSTART=FALSE\n');
        fprintf(fid, 'LDAT_ACT=LCPDAT%d\n', 2);
        fprintf(fid, 'FDAT_ACT=FP%d\n', 2);
        fprintf(fid, 'BAS(#CP_PARAMS,%.5f)\n', 0.0300);
        fprintf(fid, 'LIN XP%d C_DIS\n', 2);
        fprintf(fid, ';ENDFOLD\n');
        fprintf(fid,'WAIT SEC 4.000\n');
        % fprintf(fid, '$OUT[1] = TRUE\n');
        fprintf(fid, "OUT 1 '' STATE=TRUE\n");
% second move and onwards
    % Loop through the positions
    for i = 1:size(positions, 1)-1
        pos = positions(i+1, :);
        vel = velocities(i+1); %skip first vel as we are moving to point one at set vel
        
        % Print Position and Velocity
        % if i == 1  % making the first move from origin to pose 1 but with a reasonable velocity
        %     fprintf(fid, ';FOLD LIN P%d CONT Vel=%.5f m/s CPDAT%d Tool[4] Base[1];%%{PE}%%R 8.3.42,%%MKUKATPBASIS,%%CMOVE,%%VLIN,%%P 1:LIN, 2:P%d, 3:, 5:%.5f, 7:CPDAT%d\n', i+1, 0.0300, i+1, i+1, 0.0300, i+1);
        % else
            fprintf(fid, ';FOLD LIN P%d CONT Vel=%.5f m/s CPDAT%d Tool[4] Base[1];%%{PE}%%R 8.3.42,%%MKUKATPBASIS,%%CMOVE,%%VLIN,%%P 1:LIN, 2:P%d, 3:, 5:%.5f, 7:CPDAT%d\n', i+2, vel, i+2, i+2, vel, i+2);
        % end
        fprintf(fid, '$BWDSTART=FALSE\n');
        fprintf(fid, 'LDAT_ACT=LCPDAT%d\n', i+2);
        fprintf(fid, 'FDAT_ACT=FP%d\n', i+2);
        % if i == 1
        %     fprintf(fid, 'BAS(#CP_PARAMS,%.5f)\n', 0.0300);
        % else
            fprintf(fid, 'BAS(#CP_PARAMS,%.5f)\n', vel);
        % end
        fprintf(fid, 'LIN XP%d C_DIS\n', i+2);
        fprintf(fid, ';ENDFOLD\n');
    end
    
    % fprintf(fid, '$OUT[1] = FALSE\n');
    fprintf(fid, "OUT 1 '' STATE=FALSE\n");
    % End of Program
    fprintf(fid, 'END\n');
    
    % Close the file
    fclose(fid);
end
