function generateKUKALinearDAT(filename, axes_angles, positions, orientations, velocities)
    % positions is an Nx3 matrix with columns X, Y, Z
    % orientations is an Nx3 matrix with Euler angles: [A, B, C] in degrees
    % velocities is an Nx1 vector with velocities in m/s
    
    % Extract the individual axis angles
    A1 = axes_angles(1);
    A2 = axes_angles(2);
    A3 = axes_angles(3);
    A4 = axes_angles(4);
    A5 = axes_angles(5);
    A6 = axes_angles(6);

    % Format the file name without the extension
    [~, base_name, ~] = fileparts(filename);

    % Open the file for writing
    filename_full = strcat(base_name, '.dat');

    % Open file for writing
    
    fid = fopen(filename_full, 'w');
    
    positions = positions(2:end,:);
    orientations = orientations(2:end,:);
        if size(velocities, 1) == 1 && size(velocities, 2) > 1  % Check if x is a row vector (1, n)
          velocities = velocities';  % Transpose and store back in data_sets
        end
    
    % File Header
    fprintf(fid, '&ACCESS RVP\n');
    fprintf(fid, '&REL 1\n');
    fprintf(fid, '&COMMENT Generated by MATLAB\n');
    fprintf(fid, '&PARAM TEMPLATE = generateKUKALinearDat.m\n');
    fprintf(fid, '&PARAM EDITMASK = *\n');
    
    % Define the initial axes (XP1)
    % Use the base name in the fprintf line
    fprintf(fid, 'DEFDAT  %s\n\n', base_name);
    fprintf(fid, 'DECL E6AXIS XP1={AXIS: A1 %.6f,A2 %.6f,A3 %.6f,A4 %.6f,A5 %.6f,A6 %.6f}\n', ...
        A1, A2, A3, A4, A5, A6);
    
    % Define the FDAT for the first position (XP1)
    fprintf(fid, 'DECL FDAT FP1={TOOL_NO 4,BASE_NO 1,IPO_FRAME #BASE,POINT2[] " ",TQ_STATE FALSE}\n');
    
    % Define the PDAT for the first position (PPDAT1)
    fprintf(fid, 'DECL PDAT PPDAT1={VEL 50.000,ACC 100.000,APO_DIST 1.000,GEAR_JERK 50.0000,EXAX_IGN 0}\n');
    
    % ------------------------Edits------------------%
        pos = positions(1, :);
        ori = orientations(1, :);
        % vel = velocities(1,1);
        vel = 0.0500;
        % Print Position (E6POS) for XP2, XP3, etc.
        fprintf(fid, 'DECL E6POS XP%d={X %.3f,Y %.3f,Z %.3f,A %.3f,B %.3f,C %.3f}\n', 2, pos(1), pos(2), pos(3), ori(1), ori(2), ori(3));
        % Print FDAT for the tool and base (fixed values for each step)
        fprintf(fid, 'DECL FDAT FP%d={TOOL_NO 4,BASE_NO 1,IPO_FRAME #BASE,POINT2[] " ",TQ_STATE FALSE}\n', 2);
        % Print LDAT with velocity and other parameters
        fprintf(fid, 'DECL LDAT LCPDAT%d={VEL %.5f,ACC 100.000,APO_DIST 1.000,APO_FAC 50.0000,AXIS_VEL 100.000,AXIS_ACC 100.000,ORI_TYP #VAR,CIRC_TYP #BASE,JERK_FAC 50.0000,GEAR_JERK 50.0000,EXAX_IGN 0}\n', 2, vel);

    % Loop over each position/orientation pair
    for i = 1:(size(positions, 1)-1)
        % Position and orientation
        pos = positions(i+1, :);
        ori = orientations(i+1, :);
        vel = velocities(i+1,1);
        
        
        % Print Position (E6POS) for XP2, XP3, etc.
        fprintf(fid, 'DECL E6POS XP%d={X %.3f,Y %.3f,Z %.3f,A %.3f,B %.3f,C %.3f}\n', i+2, pos(1), pos(2), pos(3), ori(1), ori(2), ori(3));
        
        % Print FDAT for the tool and base (fixed values for each step)
        fprintf(fid, 'DECL FDAT FP%d={TOOL_NO 4,BASE_NO 1,IPO_FRAME #BASE,POINT2[] " ",TQ_STATE FALSE}\n', i+2);
        
        % Print LDAT with velocity and other parameters
        fprintf(fid, 'DECL LDAT LCPDAT%d={VEL %.5f,ACC 100.000,APO_DIST 1.000,APO_FAC 50.0000,AXIS_VEL 100.000,AXIS_ACC 100.000,ORI_TYP #VAR,CIRC_TYP #BASE,JERK_FAC 50.0000,GEAR_JERK 50.0000,EXAX_IGN 0}\n', i+2, vel);
    end
    
    % End DAT File
    fprintf(fid, 'ENDDAT\n');
    
    % Close the file
    fclose(fid);
end
